Blog.create!(user_id: "2", title: "Humanitarian crisis", content: "NYC officials present migrant plan to Mid-Island community",category: "political", author: "Paul Liotta", image_url: "https://www.silive.com/resizer/gHSwaCeGXkiyE2LVTiB-YE7FX4M=/500x0/smart/cloudfront-us-east-1.images.arcpublishing.com/advancelocal/EGP3KFQ2H5GQ5LPRWZMFSGTOYQ.JPG")
Blog.create!(user_id: "1", title: "The Statement Maxi ", content: "I have some beautiful coats in my collection, but there's none that make me feel more confident than this amazing houndstooth maxi style from Holland Cooper. Not only is the detailing exquisite but the extra long length adds that extra wow factor that can turn any simple outfit, into something infinitely cooler than it was. To rock the trend calf/ankle length is the perfect addition to your closet but if you're worried about being swamped in fabric then opt for a belted waist to cinch the look and/or structured shoulders/lapels to balance the luxurious weight of the fabric. ",category: "fashion", author: "stine Goya", image_url: "https://cdn-images.farfetch-contents.com/16/10/29/18/16102918_30324332_480.jpg")
Blog.create!(user_id: "1", title: "Fitted Never Tight", content: "There’s a key differential here – Fitted means your clothes fit you like they should do; comfortable. Figure hugging in all the right places but never tight. Tight means uncomfortable, ill-fitting in the wrong places and generally unsightly. Denim jeans are a perfect example – buy slim fit if you posses a slim or athletic figure, ensure they are the right length and finish tidily and ‘slim’ around the ankle. Avoid super-skinny fit that restrict movement, resemble leggings and leave question marks as to where your manhood could possibly be located.",category: "fashion", author: "phinic nyangate", image_url: "https://www.apetogentleman.com/wp-content/uploads/2018/03/Blackhorse-Lane-Atelier-jeans.png")
Blog.create!(user_id: "3", title: " IN THE END, YOU’RE ONLY HURTING YOURSELF", content: "It’s been a while since I’ve posted (sorry, I’m still working hard on my next book) and hadn’t planned to post but this piece from Terry on Rosie’s blog deserves to be spread far and wide.
If you are an author and you ask someone for their honest opinion of your work, don’t get upset if they give it. Book bloggers are treasures. They should be encouraged, praised, and if possible given red wine and chocolates. These wonderful people give up their time, for free, to review books. And as every book is a piece of art, whether they like it or not is subjective (if you don’t believe me, look up the one-star reviews on your favourite book).",category: "personal", author: "Dylan Hearn", image_url: "https://images.unsplash.com/photo-1422544834386-d121ef7c6ea8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c3VmZmVyaW5nfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60")
Blog.create!(user_id: "2", title: "A Pinch of Yum", content: "This creamy Red pepper pasta is seriously delicious and seriously vegan's perfectly chewy rigatoni, blistered juicy tomatoes, a creamy but cream-less roasted red pepper sauce, all sprinkled with fresh chives and bassil.",category: "Food", author: "Jordan B", image_url: "https://www.chefspencil.com/wp-content/uploads/A-Pinch-of-Yum.jpg.webp")


User.create!(username:"phinic12", password: "nyangate", bio:"enginer", password_confirmation:"nyangate")
User.create!(username:"nyangate23", password: "ogeto", bio:"doctor", password_confirmation:"ogeto")
User.create!(username:"ogeto2", password: "phinic", bio:"software developer", password_confirmation:"phinic")